### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XYABOIZ** [ectrc/snow#1]
I have a question, is this like the Zombie Server? If you implanted a gameserver into the backend, that would really be cool and I hope you have a great day. ;)

**Comment by ectrc** [comment]
## I am not sure what you mean.
I do not know what you are referring to. This is a Fortnite Private Server backend. Currently, there is no base api/server at the minute as it is still early in development. However, I plan to get them finished soon. If your question is will this support matchmaking and loading into game servers, then yes. I plan to release multiple tools and services to make the process super easy. For Example, an automatic service that handles creating servers on a dedicated machine **not** on the backend. This will allow for interaction between the game server and this backend. I maybe hope to even make a full out game server however this "project" is still early and not really ready at all.

_Please do not make any more issues that are just questions. I might make a discord server soon._
